export const library = {
    pageHome: {en: 'Home ', ru: 'Главная'},
    pageQuiz: {en: 'Quiz ', ru: 'Викторина'},
    pageGallery: {en: 'Gallery ', ru: 'Галерея'},
    title: {en: 'onlive quiz', ru: 'онлайн викторина'},
    startButton: {en: 'start quiz', ru: 'начать викторину'},
    title: {en: 'onlive quiz', ru: 'онлайн викторина'},
    greetingText: {
        en: ['Humans are surrounded by a huge variety of sounds. Some of the most pleasant are the sounds of nature, of which birdsongs are a part.',
        'How many birds do you know?',
        'How well developed is your hearing?',
        'Do you hear more than other?',
        'Can you identify a bird by its song?',
        'Press start and take the quiz!'
        ],
        ru: [
        'Человека окружает огромное разнообразие звуков. Одни из самых приятных - звуки природы, частью которых являются птицы.',
        'Как много птиц ты знаешь?',
        'Как хорошо развит твой слух?',
        'Слышишь ли ты больше, чем другие?',
        'Узнаешь ли ты птицу по ее пению?',
        'Жми старт и начни викторину!'
        ]
    },

    morning: {en: 'morning', ru: 'ое утро'},
    afternoon: {en: 'afternoon', ru: 'ый день'},
    evening: {en: 'evening', ru: 'ый вечер'},
    night: {en: 'night', ru: 'ой ночи'},
    cityPlace: {en: '[Enter sity]', ru: '[Введите город]'},
    wind: {en: 'Wind speed', ru: 'Скорость ветра'},
    windUnits: {en: 'm/s', ru: 'м/с'},
    humidity:  {en: 'Humidity', ru: 'Влажность'},
    errorWeather: {en: 'Error! City not found for ', ru: 'Ошибка! Не найден город '},
    nameSettingLanguage: {en: 'language', ru: 'выбор языка'},
    sourceImageText: {en: 'Image source:', ru: 'Источник изображения'},
    hideBlockText: {en: 'Hide blocks:', ru: 'Скрыть блоки:'},
    hideTime: {en: 'Time', ru: 'Время'},
    hideDate: {en: 'Date', ru: 'Дата'},
    hideGreeting: {en: 'Greeting', ru: 'Приветствие'},
    hideQuote: {en: 'Quote', ru: 'Цитата'},
    hideWheather: {en: 'Wheather', ru: 'Погода'},
    hidePlayer: {en: 'Player', ru: 'Аудиоплеер'},
    hideTodolist: {en: 'ToDo List', ru: 'Список дел'},
    tagChange: {en: 'change', ru: 'сменить'},
    tagLabel: {en: 'set a tag', ru: 'задайте тег'},
    titleSettings: {en: 'Settings', ru: 'Настройки'},
    titleTodolist: {en: 'ToDoList', ru: 'Список дел'},
    addTaskBtn: {en: 'Add', ru: 'Добавить'},
    taskDiscription: {en: 'Add your new todo', ru: 'Добавьте задачу'},
    titleList: {en: 'My list:', ru: 'Мой список:'},
  }