import '@/styles/main.scss'
// import index from '@/pages/index.html'
import Main from './js/main'
// import '@/styles/index.css'
// import logo from './assets/img/background.jpg'
// import json from './assets/json'
// import './pages/index.html'